### PR TITLE
Fix travis build

### PR DESCRIPTION
**Pull request by benasher44**
This fixes some minor build issues to get travis building properly again.

### CODE REVIEW

**Comment by benasher44** [comment]
> This fixes some minor build issues, which should get travis building properly again.

**Comment by benasher44** [comment]
Closed & reopened to get travis to pickup the updated config.

**Comment by benasher44** [comment]
Travis and Xcode config appear to be in good shape again; this is ready!

**Comment by mikaoj** [comment]
Awesome, thanks! :)

**Comment by benasher44** [comment]
No problem!

**Pull request merged**
