### PR TITLE
Update swift2xcode7 branch

### PR DESCRIPTION
**Pull request by hkal**
Version `1.4.1` compatibility with Xcode 7. Perhaps we can get this branch published as a pre-release target such as `1.4.1-beta`?

### CODE REVIEW

**Comment by mikaoj** [comment]
Great! I added some comments after giving it a quick look.
I'll look at it some more later, and doing a pre-release shouldn't be a problem :)

**Comment by hkal** [comment]
Thanks for the feedback, this pod is great. Looks like the tests will continue failing until this issue is resolved: https://github.com/travis-ci/travis-ci/issues/4055.

**Comment by iOSCowboy** [comment]
Just added a PR for this branch. This solves the latest errors introduced in Xcode 7.0 GM.

https://github.com/mikaoj/BSImagePicker/pull/43

**Comment by iOSCowboy** [comment]
Any updates on merging this Pr? cc @mikaoj, @hkal

**Comment by mikaoj** [comment]
Sorry for the delay, been busy both at work and at home

**Pull request merged**
