### PR TITLE
Append Swift 2.3 support

### PR DESCRIPTION
**Pull request by florentmorin**
Swift 2.3 support is included but Swift 2.2 support is maintained.

### CODE REVIEW

**Comment by michael-mckenna** [comment]
Plans on this being merged?

**Comment by florentmorin** [comment]
@michael-mckenna Currently, I use my fork as pod source: `pod 'BSImagePicker',  git: 'git@github.com:florentmorin/BSImagePicker.git'`

**Comment by michael-mckenna** [comment]
@florentmorin Thanks for the response, I got that working. That's how I was able to find the bugs ;)

**Comment by florentmorin** [comment]
@michael-mckenna Yes. I have no time to fix them for now. If it's possible for you, it can be great!

**Comment by mikaoj** [comment]
I think the crash is in BSGridCollectionViewLayout and with iOS 10. Where you running iOS 10?
And that it has been fixed in the latest version, but in a Swift 3...

**Comment by mikaoj** [comment]
@florentmorin Thanks for submitting the pull request!
I would like to move forward and not maintain Swift 2.0 backwards compatibility, so could you remove the #ifs and just make it a pure Swift 2.3 version?

**Comment by michael-mckenna** [comment]
@mikaoj I am running iOS 10 on my physical device and using Swift 2.3.

**Comment by mikaoj** [comment]
I've backported the iOS 10 bugfixes to a Swift 2.3 version: 1.2.0-swift23
If you update the dependency in BSImagePicker.podspec it should hopefully not crash anymore.

So to summarise what I would like to see in this pull request:
1. Remove the #if swift >= 2.3 #else and make this a Swift 2.3 version only
2. Update dependenies to use BSGridCollectionViewLayout 1.2.0-swift23

Is that something you will have time to fix @florentmorin ?

**Comment by florentmorin** [comment]
OK. I'll send a new pull request.

**Comment by shenyufei** [comment]
My version is 2.3. I use pod "BSImagePicker", "~> 2.4", and install BSGridCollectionViewLayout (1.2.0). But he is still being given.
3d2b558d-f930-4c49-a94d-f365dabc1148
Can you give an accurate pod install?
@florentmorin

**Comment by florentmorin** [comment]
@shenyufei `pod 'BSImagePicker', '~> 2.4.0'` should work fine. But I suggest using Swift 3. Swift 2 is no longer supported by Xcode 8.3.

**Pull request closed without merging**
