### PR TITLE
Minor adjustments, Preview Screen Title Attributes, Album Title Attributes, CurrentAuthorization, Unselect on Reaching Max Limit (if desired), Arrow in Albums button same color as albums button text

### PR DESCRIPTION
**Pull request by skela**
* Moved preview screen title attributes into theme. 
* Adds currentAuthorization method to ImagePickerController so we can check authorization of PHPhotoLibrary. Useful since if its .denied, then nothing happens on presentation, and this saves us from having to add another clojure, or for people to use delegates JUST to handle this.
* Adds some cocoa pods stuff to gitignore for the Example project.
* New unselectOnReachingMax configuration setting that causes it to unselect the first selection, when reaching the max limit (defaults to off so it does not change any current behaviour).
* Moved album title attributes into theme.
* Arrow in Albums button shown in the ImagePicker navbar when you have more than 1 album, should be the same colour as the albums button text.

### CODE REVIEW

**Comment by mikaoj** [comment]
Cool I have only only given it a quick look so far and will test and give it a proper review soon. Thanks for contributing!

So far I have one question, is the user of the image picker notified about the deselection when max is reached?

Say you have set max number of selections to 2 and unselectOnReachingMax to true.
Does it behave like this:
User selects image_1: -> select closure is called with image_1
User selects image_2: -> select closure is called with image_2
User selects image_3: -> deselect closure is called with image_1 and then select closure with image_3

**Comment by skela** [comment]
Say you have set max number of selections to 2 and unselectOnReachingMax to true.
Does it behave like this:
User selects image_1: -> select closure is called with image_1
User selects image_2: -> select closure is called with image_2
User selects image_3: -> deselect closure is called with image_1 and then select closure with image_3
User selects image_4: -> deselect closure is called with image_2 and then select closure with image_4

The deselection clojure isnt called, but ill fix that up if that's desired. Probably should, but let me know. 

It looks good UI/UX wise. UI is updated + datasource (AssetStore), just not calling that deselection clojure (forgot to test that).

**Comment by skela** [comment]
Ok, clojure called. :)

**Comment by skela** [comment]
Ok, think im done, ill stop doing stuff now so you can take a look. :)

**Comment by mikaoj** [comment]
Nice! Worked like a charm when I tested it.

Can you undo the changes to Example.xcodeproj/project.pbxproj? 
With them the example doesn't compile without having run pod install first and when it runs it complains about being linked to two BSImagePicker frameworks :)

**Comment by skela** [comment]
Example.xcodeproj/project.pbxproj reverted to what was there before, sorry about that, I couldnt get it to run without that there for some reason. 👍

**Pull request merged**
