### PR TITLE
Add a sandbox mode where taken photo are not saved into library

### PR DESCRIPTION
**Pull request by jeremierichard**
When sandbox mode is enabled, user can take photos that will not be saved in his library for privacy reasons.
I've added a new datasource called `SandboxPhotosCollectionViewDataSource` to the composed datasource.
The taken photo is holded in memory as an `UIImage` and so to manage the two types `PHAsset` and `UIImage` I had to edit the closures (selection, deselection, done, cancel) with a `AnyObject` type instead of `PHAsset` type.
I have also created a global variable `bs_selectedObjects` containing the selected items (`PHAsset` and/or `UIImage`) used to retrieve the correct selection number across different datasources.
I decided to kept the original selection array by datasource in case some tasks has to be performed on the datasource's items.
`bs_selectedObjects` is the addition of selections from `PhotosCollectionViewDataSource` and selectionImages from `SandboxPhotosCollectionViewDataSource`

### CODE REVIEW

**Comment by mikaoj** [comment]
Nice! You did it :+1: 

I'll try go through the diff sometime this week.

**Comment by jeremierichard** [comment]
Yes 👍🏼, I'm interested in receiving your feedback

**Comment by mikaoj** [comment]
Thanks for your patience, took a bit longer than promised for me to get back to you :o
I really like this feature, and it should probably be the default behavior.

I'm not a fan of closures and selections being AnyObject. Could we perhaps have UIImage and PHAsset implement a common protocol with functionality for getting size, image, etc?

**Comment by jeremierichard** [comment]
:+1: Yes this is a cleaner solution that using AnyObject Class.
I will refactor my code in this way and let you know about :)

**Pull request closed without merging**
