### PR TITLE
Issue #218 Fix non-main thread in PhotosViewController

### PR DESCRIPTION
**Pull request by sasilukr**
PR to fix https://github.com/mikaoj/BSImagePicker/issues/218

### CODE REVIEW

**Comment by benasher44** [comment]
Updating the travis yml to use xcode image 10.2 or greater should fix CI

**Comment by sasilukr** [comment]
Thank you @benasher44!

**Comment by benasher44** [comment]
Looks like now you have to remove `--no-rdoc` from `gem install xcpretty --no-rdoc --no-ri --no-document --quiet`

**Comment by sasilukr** [comment]
Hi @mikaoj - this PR is ready for a review :)

**Pull request merged**
