### PR TITLE
Exposes members to Objective-C projects

### LINKED ISSUE #248: How to use this with an Objective-C project?
This might sound like a dumb question, but, how can I use it? I've added the pod, but so far, I can only seem to get this import:
```
#import "BSImagePicker-prefix.pch"
```
Which is not I want. 

Thanks!

### PR DESCRIPTION
**Pull request by miguelpruivo**
Closes #248.

### CODE REVIEW

**Comment by miguelpruivo** [comment]
@mikaoj sorry to notify you again, but I have an ongoing project that will need to rely on this and has a feature that's waiting on this to be merged. I don't want to create a "fix pod" or manually include it on the project.

Thanks!

**Comment by mikaoj** [comment]
The changes here don't look so terrifying so I should probably be able to merge it.

I don't know what you mean by 'fix pod'. But for future reference, when you've made changes that you depend on you can always instruct your Podfile to use your fork instead.

```
pod 'BSImagePicker', :git => 'https://github.com/miguelpruivo/BSImagePicker.git'
```

**Comment by miguelpruivo** [comment]
@mikaoj thank you, I wish I could do that, but this will act as a subspec of a Pod that I have and not as a project dependency, so it's impossible to refer it as an external dependency. 😞

**Comment by miguelpruivo** [comment]
Also, and because of that, please don't forget to deploy a new version on cocoapods, otherwise I can't specify it as a subspec @mikaoj. 

Thank you very much! 🙏

**Comment by mikaoj** [comment]
Ah yeah you were using it as a dependency in your own pod, forgot about that. :)

**Comment by mikaoj** [comment]
Tagged, pushed and should be ready to use now. Thanks for contributing!

**Comment by miguelpruivo** [comment]
Thank you @mikaoj, I really hadn't the chance to explore all the properties, so if for some reason but using `@objMembers` should expose most of them. If I still need anything else, I'll issue a new PR. 

Thank you!

**Pull request merged**
