### PR TITLE
Video selection

### PR DESCRIPTION
**Pull request by calebisstupid**
Added ability to select videos with optional param "enableVideos". It is false by default.

Added 4th line to example project to demonstrate videos enabled.

### CODE REVIEW

**Comment by calebisstupid** [comment]
Any guidance on how I broke the CI build would be appreciated. I'm not super familiar with the tool chain here and not sure how 'BSImagePicker.xcworkspace' does not exist.

**Comment by mikaoj** [comment]
Nah, it's me...I began a larger refactor, most of which I havn't pushed yet, during the holidays.
Part of that was removing the cocoapods setup of the project (which was the reason for the workspace :))

**Comment by calebisstupid** [comment]
@mikaoj Not sure if you've had a chance to review this in detail yet. Just let me know if there is anything I should change to get it merged in. I'm continuing to work on our fork to add things like max video duration and other properties that I can submit PRs for if this looks good!

**Comment by calebisstupid** [comment]
Shoot. I did not realize me committing to our fork updated this PR automatically.

**Comment by dfujiwara** [comment]
@calebisstupid, do you have plans to push this further? I would love to have this feature and happy to help out!

**Comment by calebisstupid** [comment]
Unfortunately, I do not at this time. It works well, and is most definitely not clean as I barely have any iOS background.

I have it working on our project with a max length param which is all we needed. Please feel free to check out our fork and continue improving it! I was mostly focused on getting it to play nice with [flutter multi_image_picker](https://github.com/Sh1d0w/multi_image_picker), which I have also had to fork as my any PR's there won't help until the main BSImagePicker allows video.

**Comment by dfujiwara** [comment]
Okay, great thanks for letting me know @calebisstupid. I will see what I can do here.

**Comment by mikaoj** [comment]
Thanks for helping out @calebisstupid @dfujiwara ! :P 

Noticed some small things: I'm not sure that most users would care about the max duration setting and it's default value of 30.
And if video selection is supported, then there should probably be support for previewing videos as well.

I just pushed what I'm hoping to be the next major version (3.0) of the image picker in the develop branch with working video selection and preview amongst other 'improvements'.

I will still accept pull-request with bugfixes and minor features like this to the master (2.x) branch.
But any time from anyone wanting to help out is probably better spent in the develop branch :)

**Comment by dfujiwara** [comment]
@mikaoj happy to help out on the 3.0. Do you have any details on the progress or what you want to achieve?

**Comment by calebisstupid** [comment]
This is great news. I am also willing to help if I get the time since 3.0 is planned to include videos. That would allow us to get to work on https://github.com/Sh1d0w/multi_image_picker/issues/69

**Pull request closed without merging**
