### PR TITLE
Initial live photo preview support for 3.0

### PR DESCRIPTION
**Pull request by dfujiwara**
Note that I had to tweak the long press gesture recognizer to make it
work well with the tap gesture recognizer that handles full screen
toggle.

From my own experience, the build-in playbackGestureRecognizer got
activated with a simple tap gesture which didn't trigger the one created
in PreviewController.

### CODE REVIEW

**Comment by dfujiwara** [comment]
@mikaoj I saw that you wanted to support Live Photos, so I gave it a shot. Let me know what you think.

**Comment by mikaoj** [comment]
Awesome! I've been meaning to tests this before merging, but haven't found the time yet.

**Comment by dfujiwara** [comment]
@mikaoj yeah let me know how I can help! Happy to help you push 3.0 further.

**Comment by mikaoj** [comment]
I'm alive!

Awesome stuff, live preview works as expected. :P

But I noticed a couple of things:
- Animation when going to/from preview doesn't work for live photos.
- It would be nice with a badge, indicating that the photo is a live photo. Like apple does in the native image gallery. I think https://developer.apple.com/documentation/photokit/phlivephotoview/1623417-livephotobadgeimage could be used for that.

**Comment by dfujiwara** [comment]
Sounds good. Let me look into those.

**Pull request closed without merging**
