### PR TITLE
Added support for selecting videos too

### PR DESCRIPTION
**Pull request by rickrvo**
Added Video selection support and settings

Feel free to add to the main project...

### CODE REVIEW

**Comment by calebisstupid** [comment]
Is there a major reason why video support PRs have not been reviewed or rejected? I'm kind of new to the iOS world, but I am struggling finding any sort of maintained multi picker that supports video, and I'm not sure if I am missing something major here, like some iOS standard or something.

**Comment by mikaoj** [comment]
I get a lot of mails about this project, so sometimes I forget to reply to them, as in this case. My bad.

There is something strange about the history here, almost all the commits are my old commits that already are in master.

That makes this PR hard to review. So if that gets fixed I'll review it :)

**Comment by calebisstupid** [comment]
@mikaoj Totally understandable; and this PR seems far from ideal with the amount of file changes and everything. I just was noticing somewhat of a trend in lack of video selection in available libraries, and commented on this as it was the most recent I found.

I may take a stab at adding videos and submit a PR for it if it is clean.

**Comment by calebisstupid** [comment]
@mikaoj I went ahead and took a stab at added video selection here: https://github.com/mikaoj/BSImagePicker/pull/197

I just added an enableVideos flag (defaults to false so it shouldnt change anything that is there) and added a new example for videos being enabled.

**Pull request closed without merging**
