### PR TITLE
Fix CI for 3.0 version

### PR DESCRIPTION
**Pull request by dfujiwara**
- Removed some of the test files that are no longer relevant
- Removed some test cases that need to be revisited
(CameraDataSourceTests)

### CODE REVIEW

**Comment by dfujiwara** [comment]
The tests are now working but it's failing in `- pod lib lint --quick`

**Comment by mikaoj** [comment]
Yeah, I see whats wrong

**Comment by mikaoj** [comment]
Fixed, so if you merge in develop in this branch we should hopefully see a green light from travis :P

**Comment by dfujiwara** [comment]
Thanks!

**Pull request merged**
