### PR TITLE
Feature: Set default selected assets

### PR DESCRIPTION
**Pull request by AnthonyMDev**
This allows you to initialize an image picker with a `PHFetchRequest` containing images that should be selected by default.

### CODE REVIEW

**Comment by mikaoj** [comment]
Great! :+1: 
Could you extend some of the example code in the example project to show how to use it?

**Comment by AnthonyMDev** [comment]
I can do that. I'll try to put something together later today.

**Comment by barrault01** [comment]
@AnthonyMDev @mikaoj any news about this PR? I will love to use this feature.

**Comment by AnthonyMDev** [comment]
Example project updated! Hope to see this merged soon! Thanks for the ping @barrault01! I had totally forgotten about this.

**Comment by AnthonyMDev** [comment]
The CI build is saying that one of your UI tests is failing. I'm not sure why that is, as I just ran the tests on the branch on my machine, and they are all passing. It looks like it had something to do with the simulator not starting and restarting the application properly while performing the tests on the CI server. You may want to try re-running the tests.

**Comment by barrault01** [comment]
@AnthonyMDev  I believe you are right "App state is still not terminated" is due that the simulator not finished running between the 2 UI test.

**Comment by barrault01** [comment]
@AnthonyMDev I fixed it : https://github.com/mikaoj/BSImagePicker/pull/60

**Comment by mikaoj** [comment]
Great scott! Fun to see contribution to the project :+1: 
I'll have a look at your PR's this weekend and hopefully take them in and release a new version

**Pull request merged**
