### PR TITLE
add pinch-to-zoom in PreviewViewController

### PR DESCRIPTION
**Pull request by sherifnada**

### CODE REVIEW

**Comment by sherifnada** [comment]
@mikaoj Hi there! I added a simple pinch-to-zoom feature inside the PreviewViewController. 

Separate conversation: I'm also happy to implement a tap-to-zoom feature, but am less certain about the UX. Currently thinking that it should be double-tap-to-zoom until it reaches a maximum zoom level (say after 2 taps), after which double tapping returns back to original zoom level. Excited to hear your thoughts!

**Comment by sherifnada** [comment]
Not sure why the build is failing, but seems no different from the master branch.

**Comment by sherifnada** [comment]
Build can be fixed by specifying the destination (`-destination 'platform=iOS Simulator,name=iPhone 7'`) inside the travis.yml script config.

**Comment by gralexey** [comment]
@sherifnada 
>Separate conversation: I'm also happy to implement a tap-to-zoom feature, but am less certain about the UX. Currently thinking that it should be double-tap-to-zoom until it reaches a maximum zoom level (say after 2 taps), after which double tapping returns back to original zoom level. Excited to hear your thoughts!

I think double tap -> zoom in -> double tap -> zoom out should be ok!

**Pull request closed without merging**
