### PR TITLE
Add selectionType setting with checked and numbered options

### PR DESCRIPTION
**Pull request by High5Apps**
Hey @mikaoj,

Thanks for maintaining this wonderful library!
Please let me know what you need in order to have these 3 changes accepted into master.

\- Julian

### CODE REVIEW

**Comment by High5Apps** [comment]
I'm not sure why the Travis CI check isn't picking up my newly added SelectionView.swift file. Is there a manifest somewhere that I need to add new files to? Sorry, I haven't used Travis CI before.

**Comment by mikaoj** [comment]
Thanks for helping out! I'll have a look this weekend. 

As for the build failing, it looks like you haven't added the files to the project so you need to add the files to the BSImagePicker project. Either by drag and drop or right click and choose 'Add files to "BSImagePicker"'

image

**Comment by High5Apps** [comment]
Thanks for your help. It turns out I forgot to check in my .pbxproj file. All checks are now passing. Please let me know if you need clarification on any of my changes once you take a look!

**Comment by mikaoj** [comment]
I've tested it like the feature. But there are a couple of issues.

1. If I scroll a bunch of selections out of frame and then back again. They aren't shown as selected anymore
2. If I switch to another album/asset collection and make some selections there they start at 1 even if I have made selections in another album.
3. Done button isn't updated on selection.
4. If I'm making many selections they can randomly restart from 1 even if there are selections before it.
5. I had a crash once, wasn't able to reproduce it and didn't have the debugger attached. But the forceful unwrap of indexPathsForSelectedItems looks like a prime suspect to me ;)

I think you need to change to code from using indexPathsForSelectedItems for the number of selections and instead access the asset store somehow.

**Comment by mikaoj** [comment]
Done button not updating seems to be in master - ignore that one, I'll fix :)

**Comment by mikaoj** [comment]
I've fixed some of the things I found in the master branch, so update your branch.
There is now a selectedAssets function on the delegate that you probably can use for count :)

**Comment by High5Apps** [comment]
Hey thanks for fixing those issues in master and adding selectedAssets to the delegate. Monday is a holiday for us in America, but I will update and take a look at the other issues by Tuesday at the latest.

**Comment by High5Apps** [comment]
Thanks for bringing those issues to my attention. I believe that commit c3effa4 fixes them. Please let me know if you discover any remaining issues and I'll get them straightened out. Otherwise, I look forward to seeing this in master!
Thanks,
\- Julian

**Comment by High5Apps** [comment]
I removed the 2 color change commits since they're covered by skela's commits 98b3e69 and c217074. Then I squashed all of my numbered selectionType commits into a single commit. Then I rebased so it should be ready to accept. Please let me know if you need anything else.
Thanks
\- Julian

**Comment by mikaoj** [comment]
I ran it through another round of testing. And the issue where the cells aren't shown as selected when you scroll them off screen and then back is still there.

I'm doing the testing on my phone with thousands of photos and iCloud photos turned on.
And you have to scroll a bit, probably to trigger a new fetch from iCloud which might be calling the photoLibraryDidChange method.

**Comment by High5Apps** [comment]
Unfortunately, this is going to be a tough one for me to test since I only have about 250 photos and don't use iCloud. As such, I was unable to get `PHPhotoLibraryChangeObserver`'s `photoLibraryDidChange` method to fire.  However I do have 2 questions that I think could illuminate this issue:

1) Can you please confirm for me that this issue does not occur in master? 
2) Can you please explain to me the imbalance between calling `assetsViewController(_:didDeselectAsset:)` in [line 202 of AssetsViewController](https://github.com/mikaoj/BSImagePicker/blob/master/Sources/Scene/Assets/AssetsViewController.swift#L202) without also calling `assetsViewController(_:didSelectAsset:)` for the inserted indexes? Here's a screenshot of the relevant lines below.

bsimagepicker-239-0

I expect that the issue might be fixed by balancing out the code at [line 206 of AssetsViewController](https://github.com/mikaoj/BSImagePicker/blob/master/Sources/Scene/Assets/AssetsViewController.swift#L206) to look like this:
```
if let inserted = changes.insertedIndexes, inserted.count > 0 {
    let insertedItems = inserted.map { IndexPath(item: $0, section:0) }
    let insertedSelections = self.collectionView.indexPathsForSelectedItems?.filter { return insertedItems.contains($0) }
    insertedSelections?.forEach {
        self.delegate?.assetsViewController(self, didSelectAsset: changes.fetchResultAfterChanges.object(at: $0.row))
    }
    self.collectionView.insertItems(at: insertedItems)
}
```
But it's possible that `fetchResultAfterChanges` should be replaced with `fetchResultBeforeChanges` in the code suggestion above. 

If, indeed, this bug is only in my branch, would you mind testing to see if the code above fixes the issue? 

Thanks!
\- Julian

**Comment by mikaoj** [comment]
Fixed the issues found during testing and some other small stuff (I didn't work with another setting you could toggle where it unselects when reaching max) and made the font size a tiny bit smaller.

Thanks for helping out! I'll make a new release with this soon.

**Comment by High5Apps** [comment]
Thank you, thank you, thank you, @mikaoj! 
It's been wonderful working with you 🙌
Thanks again for maintaining this outstanding library!

**Pull request merged**
